// Copyright 2026 Code Philosophy
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ZenTS.CppCodeGen
{
    internal sealed class ExtensionCodegen
    {
        private readonly string _outputDir;

        public ExtensionCodegen(string outputDir)
        {
            _outputDir = outputDir;
        }

        public void Generate()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            List<JsExtensionXmlRule> rules;
            try
            {
                JsExtensionXmlRegistry.Load(Settings.Instance.jsExtensionXmlPaths, projectRoot);
                JsExtensionXmlRegistry.ValidateAllLoadedAssemblies();
                rules = new List<JsExtensionXmlRule>(JsExtensionXmlRegistry.Rules);
            }
            catch (Exception ex)
            {
                throw new Exception("[ZenTS] JsExtensions XML load/validate failed during codegen: " + ex.Message, ex);
            }

            WriteHeader();
            WriteSource(rules);
            Debug.Log("[ZenTS] ExtensionCodegen: emitted " + rules.Count + " XML rule(s).");
        }

        private void WriteHeader()
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by ExtensionCodegen. Do not edit.");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#define ZENTS_HAS_EXTENSION_BINDINGS 1");
            writer.WriteLine();
            writer.WriteLine("namespace zents");
            writer.WriteLine("{");
            writer.WriteLine("    void RegisterExtensionBindingTables();");
            writer.WriteLine("}");
            writer.Save(Path.Combine(_outputDir, "ExtensionBindings.h"));
        }

        private void WriteSource(List<JsExtensionXmlRule> rules)
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by ExtensionCodegen. Do not edit.");
            writer.WriteLine("#include \"ExtensionBindings.h\"");
            writer.WriteLine("#include \"../mt/ExtensionXmlTable.h\"");
            writer.WriteLine();
            writer.WriteLine("namespace zents");
            writer.WriteLine("{");
            writer.WriteLine("namespace extension_bindings");
            writer.WriteLine("{");

            if (rules.Count > 0)
            {
                writer.WriteLine("static const JsExtensionXmlEntry kEntries[] = {");
                writer.IncreaseIndent();
                for (int i = 0; i < rules.Count; i++)
                {
                    JsExtensionXmlRule rule = rules[i];
                    writer.WriteLine("{");
                    writer.IncreaseIndent();
                    writer.WriteLine(ToCStringLiteral(rule.TargetAssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.TargetTypeFullName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.ExtensionAssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.ExtensionTypeFullName) + ",");
                    writer.DecreaseIndent();
                    writer.WriteLine("},");
                }

                writer.DecreaseIndent();
                writer.WriteLine("};");
            }

            writer.WriteLine("} // namespace extension_bindings");
            writer.WriteLine();
            writer.WriteLine("void RegisterExtensionBindingTables()");
            writer.WriteLine("{");
            writer.IncreaseIndent();
            if (rules.Count == 0)
            {
                writer.WriteLine("ExtensionXmlTable::Clear();");
            }
            else
            {
                writer.WriteLine(
                    "ExtensionXmlTable::RegisterEntries(extension_bindings::kEntries, sizeof(extension_bindings::kEntries) / sizeof(extension_bindings::kEntries[0]));");
            }

            writer.DecreaseIndent();
            writer.WriteLine("}");
            writer.WriteLine("} // namespace zents");
            writer.Save(Path.Combine(_outputDir, "ExtensionBindings.cpp"));
        }

        private static string ToCStringLiteral(string value)
        {
            if (value == null)
            {
                return "\"\"";
            }

            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        if (c < 32 || c > 126)
                        {
                            sb.Append("\\x");
                            sb.Append(((int)c).ToString("x2"));
                        }
                        else
                        {
                            sb.Append(c);
                        }

                        break;
                }
            }

            sb.Append('"');
            return sb.ToString();
        }
    }
}
