// Copyright 2026 Code Philosophy
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ZenTS.CppCodeGen
{
    internal sealed class MarshalAsCodegen
    {
        private readonly string _outputDir;

        public MarshalAsCodegen(string outputDir)
        {
            _outputDir = outputDir;
        }

        public void Generate()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            List<JsMarshalAsXmlRule> rules;
            try
            {
                // Load + validate against Editor-loaded assemblies (name resolve; not final AOT tokens).
                JsMarshalAsXmlRegistry.Load(Settings.Instance.marshalAsXmlPaths, projectRoot);
                JsMarshalAsXmlRegistry.ValidateAllLoadedAssemblies();
                rules = new List<JsMarshalAsXmlRule>(JsMarshalAsXmlRegistry.Rules);
            }
            catch (Exception ex)
            {
                throw new Exception("[ZenTS] MarshalAs XML load/validate failed during codegen: " + ex.Message, ex);
            }

            WriteHeader();
            WriteSource(rules);
            Debug.Log("[ZenTS] MarshalAsCodegen: emitted " + rules.Count + " XML rule(s).");
        }

        private void WriteHeader()
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by MarshalAsCodegen. Do not edit.");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#define ZENTS_HAS_MARSHAL_BINDINGS 1");
            writer.WriteLine();
            writer.WriteLine("namespace zents");
            writer.WriteLine("{");
            writer.WriteLine("    void RegisterMarshalBindingTables();");
            writer.WriteLine("}");
            writer.Save(Path.Combine(_outputDir, "MarshalBindings.h"));
        }

        private void WriteSource(List<JsMarshalAsXmlRule> rules)
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by MarshalAsCodegen. Do not edit.");
            writer.WriteLine("#include \"MarshalBindings.h\"");
            writer.WriteLine("#include \"../marshal/MarshalAsXmlTable.h\"");
            writer.WriteLine();
            writer.WriteLine("namespace zents");
            writer.WriteLine("{");
            // Named (not anonymous) so Il2Cpp lumping multiple generated/*.cpp into one TU does not collide.
            writer.WriteLine("namespace marshal_as_bindings");
            writer.WriteLine("{");

            if (rules.Count > 0)
            {
                for (int i = 0; i < rules.Count; i++)
                {
                    string[] members = rules[i].Members ?? Array.Empty<string>();
                    if (members.Length == 0)
                    {
                        continue;
                    }

                    writer.WriteLine("static const char* const kMembers_" + i + "[] = {");
                    writer.IncreaseIndent();
                    for (int m = 0; m < members.Length; m++)
                    {
                        writer.WriteLine(ToCStringLiteral(members[m]) + ",");
                    }

                    writer.DecreaseIndent();
                    writer.WriteLine("};");
                    writer.WriteLine();
                }

                writer.WriteLine("static const JsMarshalAsXmlEntry kEntries[] = {");
                writer.IncreaseIndent();
                for (int i = 0; i < rules.Count; i++)
                {
                    JsMarshalAsXmlRule rule = rules[i];
                    string[] members = rule.Members ?? Array.Empty<string>();
                    string membersRef = members.Length == 0 ? "nullptr" : ("kMembers_" + i);
                    string memberName = rule.Kind == JsMarshalAsXmlTargetKind.Type
                        ? "nullptr"
                        : ToCStringLiteral(rule.Kind == JsMarshalAsXmlTargetKind.Field || rule.Kind == JsMarshalAsXmlTargetKind.Property
                            ? rule.MemberName
                            : rule.MethodName);
                    string signature = (rule.Kind == JsMarshalAsXmlTargetKind.Param || rule.Kind == JsMarshalAsXmlTargetKind.Return)
                        ? ToCStringLiteral(rule.Signature)
                        : "nullptr";
                    int paramIndex = rule.Kind == JsMarshalAsXmlTargetKind.Param ? rule.ParamIndex : -1;

                    writer.WriteLine("{");
                    writer.IncreaseIndent();
                    writer.WriteLine("JsMarshalAsXmlKind::" + rule.Kind + ",");
                    writer.WriteLine(ToCStringLiteral(rule.AssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.TypeFullName) + ",");
                    writer.WriteLine(memberName + ",");
                    writer.WriteLine(signature + ",");
                    writer.WriteLine(paramIndex + ",");
                    writer.WriteLine("JsMarshalType::" + rule.MarshalType + ",");
                    writer.WriteLine(membersRef + ",");
                    writer.WriteLine(members.Length + ",");
                    writer.DecreaseIndent();
                    writer.WriteLine("},");
                }

                writer.DecreaseIndent();
                writer.WriteLine("};");
            }

            writer.WriteLine("} // namespace marshal_as_bindings");
            writer.WriteLine();
            writer.WriteLine("void RegisterMarshalBindingTables()");
            writer.WriteLine("{");
            writer.IncreaseIndent();
            if (rules.Count == 0)
            {
                writer.WriteLine("MarshalAsXmlTable::Clear();");
            }
            else
            {
                writer.WriteLine("MarshalAsXmlTable::RegisterEntries(marshal_as_bindings::kEntries, sizeof(marshal_as_bindings::kEntries) / sizeof(marshal_as_bindings::kEntries[0]));");
            }

            writer.DecreaseIndent();
            writer.WriteLine("}");
            writer.WriteLine("} // namespace zents");
            writer.Save(Path.Combine(_outputDir, "MarshalBindings.cpp"));
        }

        private static string ToCStringLiteral(string value)
        {
            if (value == null)
            {
                return "\"\"";
            }

            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        if (c < 32 || c > 126)
                        {
                            sb.Append("\\x");
                            sb.Append(((int)c).ToString("x2"));
                        }
                        else
                        {
                            sb.Append(c);
                        }

                        break;
                }
            }

            sb.Append('"');
            return sb.ToString();
        }
    }
}
