// Copyright 2026 Code Philosophy
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System.IO;
using System.Text;
using UnityEngine;

namespace ZenTS.Utils
{
    public static class ZenTSConfWriter
    {
        public const string FileName = "ZenTSConf.inc";

        public static string LocalConfPath =>
            Path.Combine(CommonDirs.GeneratedZentsPath, FileName);

        public sealed class ConfValues
        {
            public int QuickJsVersionDate;
            public int TuanjieEngine;
            public int UnityVersion;
            public int TuanjieVersion;
            public string ConfId;
        }

        public static ConfValues Build(QuickJsVersionInfo qjsInfo, string unityVersionStr = null)
        {
            string unityStr = unityVersionStr ?? Application.unityVersion;
            var unityLine = new UnityVersion(unityStr);
            EngineVersionUtil.ResolveTuanjieFields(
                unityStr, out int tjFlag, out int tjCode, out string tjLabel);

            return new ConfValues
            {
                QuickJsVersionDate = EngineVersionUtil.EncodeQuickJsVersionDate(qjsInfo.VersionDate),
                TuanjieEngine = tjFlag,
                UnityVersion = EngineVersionUtil.EncodeUnityVersion(unityLine),
                TuanjieVersion = tjCode,
                ConfId = EngineVersionUtil.BuildConfId(qjsInfo.Id, unityLine, tjLabel),
            };
        }

        public static string FormatInc(ConfValues v)
        {
            var sb = new StringBuilder(512);
            sb.AppendLine("/* Generated by ZenTS Install/Generate. Do not edit. */");
            sb.AppendLine("#define ZENTS_QUICKJS                 1");
            sb.AppendLine($"#define ZENTS_QUICKJS_VERSION_DATE    {v.QuickJsVersionDate}");
            sb.AppendLine($"#define ZENTS_TUANJIE_ENGINE          {v.TuanjieEngine}");
            sb.AppendLine($"#define ZENTS_UNITY_VERSION           {v.UnityVersion}");
            sb.AppendLine($"#define ZENTS_TUANJIE_VERSION         {v.TuanjieVersion}");
            sb.AppendLine($"#define ZENTS_CONF_ID                 \"{EscapeCString(v.ConfId)}\"");
            return sb.ToString();
        }

        public static void WriteLocal(QuickJsVersionInfo qjsInfo, string unityVersionStr = null)
        {
            ConfValues values = Build(qjsInfo, unityVersionStr);
            string dir = CommonDirs.GeneratedZentsPath;
            Directory.CreateDirectory(dir);
            string path = Path.Combine(dir, FileName);
            File.WriteAllText(path, FormatInc(values), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            Debug.Log($"[ZenTS] Wrote {FileName}: {values.ConfId}");
        }

        private static string EscapeCString(string s) =>
            (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
