// Copyright 2026 Code Philosophy

using System.IO;
using System.Text;
using UnityEngine;

namespace ZTS.Utils
{
    public static class ZTSConfWriter
    {
        public const string FileName = "ZTSConf.inc";

        public static string LocalConfPath =>
            Path.Combine(CommonDirs.GeneratedZtsPath, FileName);

        public sealed class ConfValues
        {
            public int QuickJsVersionDate;
            public int TuanjieEngine;
            public int UnityVersion;
            public int TuanjieVersion;
            public string ConfId;
        }

        public static ConfValues Build(QuickJsVersionInfo qjsInfo, string unityVersionStr = null)
        {
            string unityStr = unityVersionStr ?? Application.unityVersion;
            var unityLine = new UnityVersion(unityStr);
            EngineVersionUtil.ResolveTuanjieFields(
                unityStr, out int tjFlag, out int tjCode, out string tjLabel);

            return new ConfValues
            {
                QuickJsVersionDate = EngineVersionUtil.EncodeQuickJsVersionDate(qjsInfo.VersionDate),
                TuanjieEngine = tjFlag,
                UnityVersion = EngineVersionUtil.EncodeUnityVersion(unityLine),
                TuanjieVersion = tjCode,
                ConfId = EngineVersionUtil.BuildConfId(qjsInfo.Id, unityLine, tjLabel),
            };
        }

        public static string FormatInc(ConfValues v)
        {
            var sb = new StringBuilder(512);
            sb.AppendLine("/* Generated by ZTS Install/Generate. Do not edit. */");
            sb.AppendLine("#define ZTS_QUICKJS                 1");
            sb.AppendLine($"#define ZTS_QUICKJS_VERSION_DATE    {v.QuickJsVersionDate}");
            sb.AppendLine($"#define ZTS_TUANJIE_ENGINE          {v.TuanjieEngine}");
            sb.AppendLine($"#define ZTS_UNITY_VERSION           {v.UnityVersion}");
            sb.AppendLine($"#define ZTS_TUANJIE_VERSION         {v.TuanjieVersion}");
            sb.AppendLine($"#define ZTS_CONF_ID                 \"{EscapeCString(v.ConfId)}\"");
            return sb.ToString();
        }

        public static void WriteLocal(QuickJsVersionInfo qjsInfo, string unityVersionStr = null)
        {
            ConfValues values = Build(qjsInfo, unityVersionStr);
            string dir = CommonDirs.GeneratedZtsPath;
            Directory.CreateDirectory(dir);
            string path = Path.Combine(dir, FileName);
            File.WriteAllText(path, FormatInc(values), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            Debug.Log($"[ZTS] Wrote {FileName}: {values.ConfId}");
        }

        private static string EscapeCString(string s) =>
            (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
